// <auto-generated />
using Angular.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Angular.Migrations
{
    [DbContext(typeof(AuctionContext))]
    [Migration("20171022184516_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Angular.Models.Bidder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BidNumber");

                    b.HasKey("ID");

                    b.ToTable("Bidders");
                });

            modelBuilder.Entity("Angular.Models.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Number");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Angular.Models.WinningBid", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BidderID");

                    b.Property<int>("ItemID");

                    b.Property<bool>("Paid");

                    b.Property<decimal>("Price");

                    b.HasKey("ID");

                    b.HasIndex("BidderID");

                    b.HasIndex("ItemID")
                        .IsUnique();

                    b.ToTable("WinningBids");
                });

            modelBuilder.Entity("Angular.Models.WinningBid", b =>
                {
                    b.HasOne("Angular.Models.Bidder", "Bidder")
                        .WithMany("WinningBids")
                        .HasForeignKey("BidderID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Angular.Models.Item", "Item")
                        .WithOne("WinningBid")
                        .HasForeignKey("Angular.Models.WinningBid", "ItemID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
